import { QRCodeSVG } from 'qrcode.react';
// import { X } from 'lucide-react';

interface QrCodeModalProps {
  url: string | null;
  onClose: () => void;
}

export function QrCodeModal({ url, onClose }: QrCodeModalProps) {
  if (!url) {
    return null;
  }

  return (
    // Backdrop
    <div 
      onClick={onClose}
      className="fixed inset-0 bg-black/70 backdrop-blur-sm flex justify-center items-center z-50 transition-opacity"
    >
      {/* Modal Panel */}
      <div 
        onClick={(e) => e.stopPropagation()} // Prevent closing when clicking inside the modal
        className="bg-white rounded-lg shadow-xl p-8 max-w-sm w-full text-center flex flex-col items-center gap-6"
      >
        <h2 className="text-2xl font-bold text-slate-800">Scan QR Code</h2>
        
        {/* QR Code generated by the library */}
        <div className="p-4 bg-white border rounded-lg">
          <QRCodeSVG 
            value={url} 
            size={256} 
            includeMargin={true}
          />
        </div>

        <a 
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="font-mono text-slate-600 hover:text-blue-600 text-sm break-all"
        >
          {url}
        </a>
        
        <button
          onClick={onClose}
          className="mt-4 bg-slate-200 hover:bg-slate-300 text-slate-800 font-bold py-2 px-6 rounded-lg transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
}
